import "./globals.css";
import Nav from "./components/Nav";
import { getServerSession } from "next-auth/next";
import { authoptions } from "@/pages/api/auth/[...nextauth]";
import Hydrate from "./components/Hydrate";
import { Roboto } from "next/font/google";
import Footer from "./components/Footer";

//font setting
const roboto = Roboto({ weight: ["400", "500", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Pete Store",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //Fetch user
  const session = await getServerSession(authoptions);

  return (
    <html className={`${roboto.className}`} lang="en" data-theme="lofi">
      <body className={` ${roboto.className}`}>
        <div className="min-h-screen mx-4 lg:mx-48">
          <Hydrate>
            <Nav user={session?.user} expires={session?.expires as string} />
            {children}
          </Hydrate>
        </div>
        <footer className="pt-20 static bottom-0">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
